### PR TITLE
Take region end in account when sorting memory map.

### PR DESCRIPTION
**Pull request by j-lthr**

### CODE REVIEW

**Comment by phil-opp** [comment]
Thanks for the PR! The change looks good to me. However, doesn't this mean that we have overlapping regions?

**Comment by j-lthr** [comment]
Thanks for the quick response.

Overlapping regions could occur temporarily in situations where someone adds a new region before changing the start of the next one or the end of the last one. 

In my opinion this small mistake shouldn't lead to undefined ordering.

(I made that small mistake)

**Comment by phil-opp** [comment]
Makes sense! Just wanted to make sure that we don't have any bug that leads to overlapping regions.

**Comment by phil-opp** [comment]
Published as version 0.2.1

**Pull request merged**
